-- Append-only domain event log — real event-sourcing-style record of every domain mutation
-- (transaction committed/settled, workflow committed/rolled back, reconciliation unmatched,
-- compliance flags, agent action flagged). NOT an event bus: written in the same @Transactional
-- as the mutation it records, per CLAUDE.md's "Event publishing — MVP rule (NO event bus)".
-- FORCE ROW LEVEL SECURITY ensures even the table owner cannot bypass RLS, matching audit_log
-- (V4) and agent_audit_events (V19). Written from within existing tenant-scoped request-path
-- transactions only (not a cross-tenant background job), so unlike webhook_outbox this has no
-- service_cross_tenant_read policy — a plain tenant_read/tenant_insert pair is correct.
--
-- reference_id/reference_type give each event an un-overloaded pointer to what it's about,
-- instead of webhook_outbox's pattern of reusing its transaction_id column to also carry a
-- workflowPlanId. correlation_id carries the request-scoped trace ID already generated by
-- TraceIdFilter (X-Idem-Trace-Id / MDC), letting every event from one originating request —
-- or one multi-step agent workflow — be joined together, including by external/other bounded
-- contexts that already see that header echoed back to them.
CREATE TABLE domain_events (
    id             UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id      UUID        NOT NULL,
    event_type     TEXT        NOT NULL,
    reference_id   UUID        NOT NULL,
    reference_type TEXT        NOT NULL,
    correlation_id TEXT        NOT NULL,
    payload        JSONB       NOT NULL,
    occurred_at    TIMESTAMPTZ NOT NULL,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT chk_domain_events_event_type
        CHECK (event_type IN (
            'TRANSACTION_COMMITTED',
            'TRANSACTION_SETTLED',
            'RECONCILIATION_UNMATCHED',
            'RECONCILIATION_EXCEPTION',
            'WORKFLOW_COMMITTED',
            'WORKFLOW_ROLLED_BACK',
            'COMPLIANCE_TRAVEL_RULE_REQUIRED',
            'AGENT_ACTION_FLAGGED'
        )),
    CONSTRAINT chk_domain_events_reference_type
        CHECK (reference_type IN ('TRANSACTION', 'WORKFLOW'))
);

CREATE INDEX idx_domain_events_tenant      ON domain_events (tenant_id, occurred_at DESC);
CREATE INDEX idx_domain_events_reference   ON domain_events (reference_id);
CREATE INDEX idx_domain_events_correlation ON domain_events (correlation_id);

ALTER TABLE domain_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE domain_events FORCE ROW LEVEL SECURITY;

CREATE POLICY tenant_read ON domain_events
    FOR SELECT
    USING (tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::UUID);

CREATE POLICY tenant_insert ON domain_events
    FOR INSERT
    WITH CHECK (tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::UUID);

REVOKE UPDATE, DELETE ON domain_events FROM PUBLIC;
