package finance.idem.core.security

enum class ApiScope {
    TRANSACTIONS_READ, TRANSACTIONS_WRITE,
    ACCOUNTS_READ, ACCOUNTS_WRITE,
    AGENTS_EXECUTE, AGENTS_AUDIT_READ,
    RECONCILIATION_READ, RECONCILIATION_WRITE,
    COMPLIANCE_EXPORT, WEBHOOK_MANAGE,
    ADMIN
}
